### ISSUE TITLE
TODO: diff for build-script

### ISSUE THREAD

**Issue by looooo** [conda-forge/coin3d-feedstock#13]
https://bitbucket.org/Coin3D/coin/issues/175/coin-build-errors-with-linux-and-osx

- [ ] remove `include_directories(${CMAKE_INSTALL_PREFIX}/include)` from patch
- [ ] remove Boost_LIBRARY_DIR:FILEPATH=$PREFIX/lib` from build-script
- [ ] `COIN_LINK_LIBSIMAGE="dynamic"` -> `SIMAGE_RUNTIME_LINKING:BOOL=ON`

**Comment by looooo** [comment]
- [ ] simplify deendencies:
```
        - {{ cdt('libxdamage') }}  # [linux]
         - {{ cdt('libselinux') }}  # [linux]
         - {{ cdt('libXxf86vm') }}  # [linux]
+        - {{ cdt('libxi-devel') }}  # [linux]
         - cmake
         - ninja
     host:
         - boost-cpp
         - libglu  # [linux]
         - xorg-libxt  # [linux]
-        - xorg-libxmu  # [linux]
-        - xorg-libxi  # [linux]
         - expat
     run:
         - boost-cpp
         - libglu  # [linux]
         - xorg-libxt  # [linux]
-        - xorg-libxmu  # [linux]
-        - xorg-libxi  # [linux]
         - expat
```
